### ISSUE TITLE
findMRCA

### ISSUE THREAD

**Issue by tpall** [agormp/treetool#1]
There is no such function as `findMRCA()` in phylotreelib (v1.27.0), it's `find_mrca()`

```
Traceback (most recent call last):
  File "treetool.py", line 301, in <module>
    main()
  File "treetool.py", line 285, in main
    analyze_tree(options, tree)
  File "treetool.py", line 199, in analyze_tree
    mrca = tree.findMRCA(leaves)
AttributeError: 'Tree' object has no attribute 'findMRCA'. Did you mean: 'find_mrca'?
```

Changing line 199 to:
```
mrca = tree.find_mrca(leaves)
```
fixes this error
 
https://github.com/agormp/treetool/blob/3415748cce6c43b4239fb56cd4e16cc1dea2c373/treetool.py#L199C9-L199C37

Cheers!

**Comment by agormp** [comment]
Thanks! Corrected now.
